### ISSUE TITLE
Fix exceptions when copying empty JWTs

### ISSUE THREAD

**Issue by harlyh** [novotnyr/jwt-intellij-plugin#1]
Reporting an issue. I was going crazy while trying to get 2 tcp sockets working from within one single script. Something kept crashing all the time (or hanging) - and then all of sudden saw a red exclamation mark blinking in bottom right corner of my PyCharm - and when I clicked on it, I saw this 

![pycharm64_2017-09-10_11-58-08](https://user-images.githubusercontent.com/30772586/30248434-ba929baa-961f-11e7-99b2-bdc5fe773c66.png)

After disabling (like suggested) my weird unrelated programming issue was gone too. 

Make of it what you will. I thought it'd be still good to report this.

**Comment by novotnyr** [comment]
Thanks for reporting!

This is caused by mishandled copying of empty JWT string to clipboard.
