### ISSUE TITLE
Line breaks in private keys not working

### ISSUE THREAD

**Issue by Rhadros** [novotnyr/jwt-intellij-plugin#17]
I cannot copy & paste any keys into the private key text field successfully. The multi-line keys are transformed into one line.

**Steps to reproduce**
* Add a JWT (alg RS256) into the JWT box.
* Text boxes for public & private keys are shown
* Try to copy a valid private key into the textbox
* Error message "Unable to parse RSA private key" is shown

When adding the key manually the enter key also not working in the text box, and the settings option for files as default is also not working.

**Comment by novotnyr** [comment]
Fixed in v0.11
