### ISSUE TITLE
Add usage instructions to README

### ISSUE THREAD

**Issue by DaBlick** [novotnyr/jwt-intellij-plugin#18]
Could you please put in the README and what not a brief instruction on how to invoke this?

**Comment by novotnyr** [comment]
Sure! 

Meanwhile, after installation, you should see the JWT plugin in the right section (see image below).

Alternatively, you can display that via menu *View -> Tool Windows -> JWT*.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/1109928/80302511-c8b95280-87aa-11ea-96c1-e69784cfe766.png">

**Comment by DaBlick** [comment]
Ah.... got it.    Thanks.   And thanks for being open to the suggestion of more documentation.
