### ISSUE TITLE
Specify icon for tool window in new UI

### ISSUE THREAD

**Issue by nobel6018** [novotnyr/jwt-intellij-plugin#26]
There is no icon in [New UI](https://www.jetbrains.com/help/idea/new-ui.html) environment.
The default icon is "?". It is not intuitive.

**Comment by nobel6018** [comment]
<img width="151" alt="Screenshot 2023-06-06 at 3 22 20 PM" src="https://github.com/novotnyr/jwt-intellij-plugin/assets/31664132/9438df65-655f-4323-9fcf-684bf33c6d85">

**Comment by novotnyr** [comment]
Fixed in a3ebde8a7fb626d04b1914bf28235008872bfbb3.
