### ISSUE TITLE
Warning Compatibility with latest Intellij (2023.1.2)

### ISSUE THREAD

**Issue by nobel6018** [novotnyr/jwt-intellij-plugin#27]
There is warning compatability with latest Intellij

<img width="1044" alt="Screenshot 2023-06-06 at 3 25 08 PM" src="https://github.com/novotnyr/jwt-intellij-plugin/assets/31664132/14913986-a8d7-4d02-9463-83dac89dcef5">

**Comment by novotnyr** [comment]
Fixed.
